 name: Docker Image CI




on:

  push:

    branches: [ test_docker ]




jobs:




  build:




    runs-on: ubuntu-latest




    steps:

    - uses: actions/checkout@v3

    - name: Build the Docker image

      run:  chmod 777 test_docker/run.sh && Now=Mck_Dev$(date +"%m-%d-%y-%H-%M-%S") && docker build test_docker/. --file test_docker/Dockerfile -t docker.io/dockertejdeep123/dockerimage:$Now && docker login docker.io -u sunitha.kotta@ovaledge.com -p Ovaledge@9795 && docker push docker.io/dockertejdeep123/dockerimage:$Now
