 name: Docker Image CI




on:

  push:

    branches: [ test_docker ]




jobs:




  build:




    runs-on: ubuntu-latest




    steps:

    - uses: actions/checkout@v3

    - name: Build the Docker image

      run:  chmod 777 docker/run.sh && Now=test_docker$(date +"%m-%d-%y-%H-%M-%S") && docker build docker/. --file docker/Dockerfile -t docker.io/dockertejdeep123/dockerimage:$Now && docker login docker.io -u sunitha.kotta@ovaledge.com -p Ovaledge@9795 && docker push docker.io/dockertejdeep123/dockerimage:$Now
