name: Docker Image CI




on:

  push:

    branches: [ test_docker ]




jobs:




  build:




    runs-on: windows




    steps:

    - uses: actions/checkout@v3

    - name: Build the Docker image

      run:  chmod 777 C:/Users/Admin/Downloads/test_jenkins/docker/run.sh && Now=Mck_Dev$(date +"%m-%d-%y-%H-%M-%S") && docker build Dev/. --file C:/Users/Admin/Downloads/test_jenkins/docker/Dockerfile -t docker.io/dockertejdeep123/dockerimage:$Now && docker login docker.io -u sunitha.kotta@ovaledge.com -p Ovaledge@9795 && docker push docker.io/dockertejdeep123/dockerimage:$Now
